Pan 43
BAleipzigCS19/pdf-extraction pull request #20
Opened 2021-11-04 16:12 UTC by WillyTheBee

2021-11-04 23:49 UTC, krankkkk requested changes
Den einen Fehler-Titel noch hinzufügen dann ist das durch

2021-11-04 23:49 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/client/controller/ImportController.java
> +
Warum ist das wieder drinnen?

2021-11-04 23:49 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/client/controller/MenuBarController.java
> +
Warum ist das drinnen?

2021-11-04 23:49 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/client/utils/AlertUtils.java
> +        showAlert(Alert.AlertType.ERROR, "Error", null, getStandardMessage() + errorMessage);
Den Titel hast du vergessen

2021-11-04 23:49 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/client/utils/LanguageHandler.java
> +        // ist current Bundle == null oder ist nicht equal der Default Locale wird das entsprechende Ressource Bundle geladen
Kommentare in englisch halten und das braucht hier ja nicht sein oder?

2021-11-06 17:24 UTC, krankkkk requested changes

2021-11-06 17:24 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/client/utils/AlertUtils.java
> +
Was macht das hier, das ist doch eine rein statische Util-Klasse

2021-11-07 16:00 UTC, WillyTheBee commented on Client/src/main/java/de/baleipzig/pdfextraction/client/utils/AlertUtils.java
> +
stimmt, wird auch gar nicht genutzt, war wohl ein relikt aus vorherigen code :D

2021-11-08 16:43 UTC, krankkkk approved these changes

2021-11-08 16:43 UTC, merged