PAN-54
BAleipzigCS19/pdf-extraction pull request #25
Opened 2021-11-24 13:30 UTC by MartinSpiegel

- begonnen

2021-11-26 19:34 UTC, krankkkk requested changes
funktionert nicht siehe Discord

2021-11-30 08:51 UTC, WillyTheBee reviewed
ist das Fertig in 32 Zeilen ? :D
![image](https://user-images.githubusercontent.com/73277466/144015192-c066d8b4-128e-4721-8fed-d5768b9d086f.png)
Bei Mir Funktioniert der Branch nicht mehr, muss ich da erst wieder die Datenbank Löschen ? 
Ich bekomme immer diese Fehlermeldung

Backend sagt: 
![image](https://user-images.githubusercontent.com/73277466/144015928-8329b4e8-2ddd-4feb-8492-f4611f0f2156.png)

2021-11-30 11:58 UTC, MartinSpiegel commented
> ist das Fertig in 32 Zeilen ? :D ![image](https://user-images.githubusercontent.com/73277466/144015192-c066d8b4-128e-4721-8fed-d5768b9d086f.png) Bei Mir Funktioniert der Branch nicht mehr, muss ich da erst wieder die Datenbank Löschen ? Ich bekomme immer diese Fehlermeldung
> 
> Backend sagt: ![image](https://user-images.githubusercontent.com/73277466/144015928-8329b4e8-2ddd-4feb-8492-f4611f0f2156.png)

hab gerade nochmal bei mir probiert, da funktioniert es

2021-11-30 11:58 UTC, MartinSpiegel commented
[KündigungKFZ.odt](https://github.com/BAleipzigCS19/pdf-extraction/files/7625507/KundigungKFZ.odt)

2021-11-30 21:16 UTC, krankkkk commented
Leute lest bitte die Fehlermeldung, das ist ein zwei-teiliges Problem
1. Es wurde kein Name gefunden aus der Quelle
2. Keinerlei Checks im Code

2021-12-02 16:01 UTC, closed without merging