Pan 21
BAleipzigCS19/pdf-extraction pull request #8
Opened 2021-10-07 15:33 UTC by MartinSpiegel

2021-10-07 17:21 UTC, krankkkk requested changes
Die ganzen Klassen `... implements FieldTypeBase` sind eigentlich nutzlos, weil man die im Code nicht benutzten kann

2021-10-07 17:21 UTC, krankkkk commented on Client/src/test/java/de/baleipzig/pdfextraction/fieldtype/FieldTypesTest.java
> +        assertEquals("Versicherungsnummer", fieldTypes.get(3).getName());
Warum testes du die hardcodierten werte eines Enums, und dann noch das die an einer bestimmten stelle sind?

2021-10-07 17:21 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/controller/CreateTemplateController.java
> +    }
Testen ob von jedem Types genau 1 benutzt wurde?

2021-10-07 17:21 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/api/AddressBase.java
> +    public AddressBase(String title, String name, String street, String postcode, String town) {
Das sollte `protected` sein, da man das nicht direkt benutzen sollte

2021-10-07 17:21 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/api/AddressBase.java
> +public class AddressBase extends ApiBase{
`equals`, `toString` und `hashcode` fehlen

2021-10-07 17:21 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/api/ApiBase.java
> +}
Warum existiert das?

2021-10-07 17:21 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/fieldtype/FieldTypeBase.java
> +    ApiBase analyze(String text);
Da eine `ApiBase` nichts ist (hat keinerlei Methoden) kann man da auch nichts analysieren

2021-10-07 17:21 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/fieldtype/FieldTypes.java
> +    public void setName(String name) {
Auf kein Fall darf man bei einem Enum den Wert verändern

2021-10-07 17:25 UTC, MartinSpiegel commented on Client/src/main/java/de/baleipzig/pdfextraction/api/AddressBase.java
> +public class AddressBase extends ApiBase{
brauchen wir das immer?

2021-10-07 17:26 UTC, MartinSpiegel commented on Client/src/main/java/de/baleipzig/pdfextraction/fieldtype/FieldTypes.java
> +    public void setName(String name) {
ok

2021-10-07 17:41 UTC, MartinSpiegel commented on Client/src/main/java/de/baleipzig/pdfextraction/api/AddressBase.java
> +    public AddressBase(String title, String name, String street, String postcode, String town) {
ok

2021-10-10 15:24 UTC, krankkkk requested changes

2021-10-10 15:24 UTC, krankkkk commented on Client/src/main/java/de/baleipzig/pdfextraction/api/AddressBase.java
> +    protected String getTitle() {
Die Getter/Setter sollten schon public sein, nur der Construktor nicht

2021-10-10 15:24 UTC, krankkkk commented on Client/src/test/java/de/baleipzig/pdfextraction/fieldtype/FieldTypesTest.java
> +        assertTrue(fieldTypes.contains(FieldTypes.INSURANCE_NUMBER));
Es gibt `containsAll`, oder ein equals mit einer manuell erstellten Liste

2021-10-10 16:43 UTC, MartinSpiegel commented on Client/src/main/java/de/baleipzig/pdfextraction/api/ApiBase.java
> +}
weil man im Interface FieldTypeBase dann bei der Methode "analyze" ein Objekt welches von der Klasse ApiBase erbt zurückgeben kann (was ja Adresse, InsuranceNumber usw. tun)

2021-10-10 16:54 UTC, MartinSpiegel commented on Client/src/test/java/de/baleipzig/pdfextraction/fieldtype/FieldTypesTest.java
> +        assertTrue(fieldTypes.contains(FieldTypes.INSURANCE_NUMBER));
so?

2021-10-12 12:23 UTC, merged